language: java

jdk:
  - openjdk-ea
  - openjdk13
  - openjdk12
  - openjdk11
  - openjdk8

services:
  - docker
  - redis-server

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

notifications:
  email: false

env:
  global:
    - secure: "X5ZMJt97OLRrBc8QZXrbbWuGYWDAoqCffcIwvVWLmvg00gZh+b5Sj/8KR3Fkl7xwLZReJvvVsbyxnmcXa4MhXrh+0Tl8NoXYmsVpoyVKkjQ6+Cf7L/4HO2WLYQ6Sfw7mQ9sFePIDiindeCwl32TDdwCrxP+rx8jB6Ppof6AmZadIkFctMtEi5TVs57oR5mR9NlS6uv6NGNzAzrBXbqFXoL0fzGxu7l0oJrndk2XjMgkosujzCLZjkV+ZML4NbZugMBSnr0y9aFF5HMRLO/BibMu7x6Lj0Ei4rGDMsG7nTmQeChVX5A2nckBfZmy3IAJznZmV/LslXXnbiOvhEEJDt0ahsiQJulZty7QRWfsTWtWEUmT1GcjZuPtFa/8OaiR0/hKAiWBXSNHizDspFQg0az6Rbh/u+N6UiIw6V0Cw7JIK9JvB7Ip6q7poJrviTQLmYDse44Kce1BRi4ih19QJwJzm5Vhm+4gw5OiE3x+85z3kxhf0RiihD1ZV/fBJ9PAR9wcGvO04lbUJZPtGGNbSiweHJV/BVrwxAqoZrqi9MoVmx/34iM8dlgYOIICR9KOgA1EnM+Fc0z0vbK8cN4/ByruuZiYXWskkdtXZVA2qPmGwrqkFtxJxBq+5tJUsKXs4g1eYejGslejPnLyMVeTpOJcBp+0SwpBW/N++V8jsChU="

addons:
  sonarcloud:
    organization: "fartherp"
    token:
      secure: "FxCigbKJonHxjq7bF/rRyTaJ6AHaJIIX8bdfa3CQQ/noZMjfKbrDrcnJDiDss4oCA7TNmQTuXWW+klzs3xVsu5frbB3UKLCtp+urNsW9uOa3U13B6Cbas1z7RSSk4SsOD632ehNUOufptH4qgGtjPKnBG+w/LAei96VrWnb3cenT3vUijwiAL9LdI+RumF73LH+9WIS36K5rBfmAvQOLEWVIU7p46a+WipqC9l8/0fNC3cnZ/fSCxZ0RxQdB30nyFf+lfoH/TaHeXEfPSgwRtCunbke1vzTUmv6lPL7HlHEVTDYc7ncaJ32KcNcy2FkDZWbha2nwzwsZn1CBl9gioJEnpLd+UPWYlo6/rNWD6v57kI89YbUAL9X3b2mcIxhGo+T5cvCieidhPu90tRbvcWnkbYSd1NV06Yv/WZYsa9gocIrTbFr86VMK7SnCDso92XWbJCGzTq4AJLioRgDkd+AGu5u2KJyjq78va9+A2dA1JuWle+6Q8kx+HbmORPCunbQrPdhpen7z0Z+/i6DuK9WIu0bcsoJrRhkW+cDqTb45g247Yf5ss8wFCmCSWBwyph11JhYbNg8oHEL/vg5e5gJ618twCvvS09/wEB6fhbMlpPPuPdWLvoSDsFTwr1fMCOpyM6VefrVVUC/TNCRSoDL4J3MmX9ekW8ykNik5pjE="